esphome:
  name: emerald-ems
  friendly_name: Emerald EMS

esp32:
  board: upesy_wroom
  framework:
    type: arduino

external_components:
  - source: github://bdshields/esphome_emerald_ble@main
    components: [ ble_client, esp32_ble_tracker, emerald_ble ]

# Find these details on the device
substitutions:
  ble_client_mac_address: "xx:xx:xx:xx:xx:xx"
  sensor_pairing_code: "xxxxxx"
  sensor_pulses_per_kwh: "1000"

api:

# Enable logging
logger:
  level: debug
  baud_rate: 0

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "emeraldble Fallback Hotspot"
    password: !secret wifi_ap_password

# optional requirement used with daily energy sensor
time:
  - platform: homeassistant
    id: homeassistant_time

esp32_ble_tracker:

ble_client:
  - mac_address: ${ble_client_mac_address}
    id: emerald_advisor

sensor:
  - platform: emerald_ble
    ble_client_id: emerald_advisor
    power:
      name: "Emerald Power"
      filters:
      - sliding_window_moving_average:
          window_size: 2
          send_every: 1
    daily_energy:
      name: "Emerald Daily Energy"
    energy:
      name: "Emerald Total Energy"
    battery_level:
      name: "Emerald Battery"
    pairing_code: ${sensor_pairing_code}
    pulses_per_kwh: ${sensor_pulses_per_kwh}
    time_id: homeassistant_time # daily energy still works without a time_id, but recommended to include one to properly handle daylight savings, etc.
